# Generated by Django 4.1.2 on 2022-10-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('rangeid', models.AutoField(primary_key=True, serialize=False, verbose_name='rangeId')),
                ('rangename', models.CharField(max_length=30, unique=True, verbose_name='rangeName')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False, verbose_name='modelId')),
                ('modelname', models.CharField(max_length=30, unique=True, verbose_name='modelName')),
                ('producer', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=30, null=True)),
                ('idrange', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='l5.range', verbose_name='idRange')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False, verbose_name='itemId')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large'), ('XXL', 'Extra extra large')], default='M', max_length=4)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('idmodel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='l5.models', verbose_name='idModel')),
            ],
            options={
                'unique_together': {('idmodel', 'size')},
            },
        ),
    ]
